version: "3.9"
services:
    app:
        build:
            context: ./app
        ports:
            - "8080:8080"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "5000:5000"